# Generated by Django 3.1.7 on 2021-03-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.CharField(max_length=124),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=124),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='mm.category'),
        ),
    ]
